sudo: true

matrix:
  include:
    - os: linux
      env: LAZ_VER=1.6 LAZ_ENV=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
    - os: linux
      dist: trusty

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0

before_install:
  - tools/travis/before_install.sh

install:
  - tools/travis/install.sh

script:
  - tools/travis/build.sh
